### ISSUE TITLE
Remove text shadow

### ISSUE THREAD

**Issue by crystalfp** [eliortabeka/tootik#8]
The button to which I added tootik tooltip has text-shadow for the button label, so the tooltip has text shadow too. Unfortunately this makes the label quite unreadable. As a quick and dirty workaround I added `[data-tooktik]:after {text-shadow: none}` to my application main css file.
Is there any cleaner method to remove this shadow?
Thanks!
mario

**Comment by eliortabeka** [comment]
Hi Mario, Thank's for pointing out.
In the next release I will include this.
